### ISSUE TITLE
[feature request] HTMLUnSerializer

### ISSUE THREAD

**Issue by joergwasmeier** [Blank101/haxe-dom#30]
Perhapses it is possible to create something similar than React has with JSX?

**Comment by Blank101** [comment]
To parse an html fragment? There is already an Unserializer located here: https://github.com/Blank101/haxe-dom/blob/master/src/hxdom/js/Boot.hx, but it is intended to be used only upon page load.

Although hxdom does share a lot of similarities with React, the way views are handled are quite different. In particular there is no free-form HTML unless you absolutely need it. Web apps using hxdom should be constructed by extending the virtual dom elements and implementing logic inside these isolated components which you can then string together programatically.

**Comment by joergwasmeier** [comment]
HI thanks for the Reply, the Idea behind ist to use XML to create your layout. In example we take the basic stuff.

var page = new EHtml();
var head = new EHead();
var body = new EBody();

page.appendChild(head);
page.appendChild(body);

Wouldn´t it be nice if you can write somthing like:

HaxeDom.registerComponent("EHtml", EHtml);
HaxeDom.registerComponent("EHead", EHtml);
HaxeDom.registerComponent("EBody", CustomBody);

var dom:Map<String, VirtualNode> = HaxeDom.parse("<EHtml id="page"><EHead id="head"></EHead><CustomBody id="body"></CustomBody></EHtml>");
trace(dom.get(body));

So you can write your custom HTML Tags create your Layouts with XML and get after taht an VirtualDom for Isomorphic Apps.

Its just an idea.

**Comment by Blank101** [comment]
It's an interesting idea. Personally I probably won't be implementing this, but I'm open to PRs if it's built in an appropriate way.
